
version: '3'
services:
  telegram-bot:
    container_name: telegram-bot
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TG_API_KEY: 
    depends_on: 
      - mongo


  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest